version: '3'

includes:
  cargo:
    taskfile: ../../mono-dev/task/cargo.yaml
    optional: true
    internal: true

tasks:
  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check
  fix:
    - task: cargo:fmt-fix
